name: Update README with Countdown

on:
  schedule:
    - cron: '0 17 * * *' # Menjalankan setiap hari pada pukul 17:00 UTC (00:00 UTC+7)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Jika menggunakan pytz, uncomment baris berikut
          # pip install pytz

      - name: Calculate days remaining
        id: countdown
        run: |
          from datetime import datetime
          try:
              from zoneinfo import ZoneInfo
          except ImportError:
              from backports.zoneinfo import ZoneInfo  # Untuk versi Python < 3.9

          # Tentukan zona waktu Jakarta
          jakarta_tz = ZoneInfo("Asia/Jakarta")

          # Tentukan deadline
          deadline = datetime(2024, 12, 23, tzinfo=jakarta_tz)

          # Dapatkan tanggal hari ini di zona waktu Jakarta
          today = datetime.now(jakarta_tz).date()

          delta = deadline.date() - today
          days_left = delta.days

          # Pastikan hari tidak negatif
          if days_left < 0:
              days_left = 0

          print(f"DAYS_LEFT={days_left}")
          # Menyimpan output agar bisa digunakan di langkah berikutnya
          # Perhatikan bahwa 'set-output' sudah deprecated, gunakan GITHUB_OUTPUT
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"days={days_left}\n")

      - name: Update README
        run: |
          DAYS_LEFT=${{ steps.countdown.outputs.days }}
          # Mengganti 'XXX hari lagi' dengan jumlah hari yang tersisa
          sed -i "s/XXX hari lagi/${DAYS_LEFT} hari lagi/" README.md

      - name: Commit and push changes
        run: |
          DAYS_LEFT=${{ steps.countdown.outputs.days }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update countdown: ${DAYS_LEFT} hari lagi"
          git push
