name: Update README Deadline Countdown

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Update Deadline Countdown
      run: |
        from datetime import datetime, timezone
        
        # Calculate remaining days
        deadline = datetime(2024, 12, 23, tzinfo=timezone.utc)
        now = datetime.now(timezone.utc)
        remaining_days = (deadline - now).days
        
        # Read existing README content
        with open('README.md', 'r') as file:
            readme_lines = file.readlines()
        
        # Update or add deadline line
        if readme_lines and readme_lines[0].startswith('``` Deadline'):
            readme_lines[0] = f'``` Deadline : {remaining_days} hari lagi.```\n'
        else:
            readme_lines.insert(0, f'``` Deadline : {remaining_days} hari lagi.```\n')
        
        # Write updated content back to README
        with open('README.md', 'w') as file:
            file.writelines(readme_lines)
      shell: python
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update deadline countdown" && git push)
